spring:
  profiles:
    active: dev
--- 
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update