spring:
  profiles:
    active: production

--- 
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: production
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    tomcat: 
      validation-query: SELECT 1
      test-on-borrow: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
