spring:
  profiles:
    active: dev
--- 
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: production
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
    dbcp:
      test-on-borrow: true
      validation-query: SELECT 1
    tomcat: 
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
